name: Codex – Auto Fix on CI Failure

on:
  workflow_run:
    workflows: ["Flutter Web -> Firebase Hosting (prod + previews)"]
    types: [completed]

permissions:
  contents: write
  pull-requests: write
  issues: write
  actions: read
  checks: read

jobs:
  analyze-and-fix:
    if: ${{ github.event.workflow_run.conclusion != 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm ci

      - name: Run Codex fixer
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node .github/scripts/codex-fix.js
