name: Codex – Issue Watcher

on:
  issues:
    types: [opened, edited, labeled]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  codex-issue-watcher:
    if: >
      github.event.issue.state == 'open' &&
      (
        contains(github.event.issue.body, '@codex') ||
        contains(join(fromJson(toJson(github.event.issue.labels)).*.name, ','), 'feature') ||
        contains(join(fromJson(toJson(github.event.issue.labels)).*.name, ','), 'bug')
      )
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci

      - name: Run Codex Issue Handler
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node .github/scripts/codex-issue.js
