name: Flutter Web -> Firebase Hosting (prod + previews)

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write
  checks: write
  deployments: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}           # cancel older runs on same branch
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Cache Flutter SDK
      - name: Cache Flutter SDK
        uses: actions/cache@v4
        with:
          path: ~/.flutter
          key: flutter-${{ runner.os }}-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            flutter-${{ runner.os }}-

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true   # enables built-in pub cache too

      # Extra cache for build + pub (helps a lot)
      - name: Cache pub and build
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            apps/app_flutter/.dart_tool
            apps/app_flutter/build
          key: pub-${{ runner.os }}-${{ hashFiles('apps/app_flutter/pubspec.lock') }}
          restore-keys: |
            pub-${{ runner.os }}-

      - name: Build Flutter web
        working-directory: apps/app_flutter
        run: |
          flutter config --enable-web
          flutter pub get
          flutter build web --release

      # Preview deploy for PRs
      - name: Deploy to Firebase Hosting (preview for PRs)
        if: ${{ github.event_name == 'pull_request' }}
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
          entryPoint: "./"
          channelId: pr-${{ github.event.number }}

      # Production deploy on push to main
      - name: Deploy to Firebase Hosting (production)
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
          entryPoint: "./"
          channelId: live
