name: Flutter Web -> Firebase Hosting (prod)

on:
  workflow_dispatch: {}        # allow manual "Run workflow" button
  push:
    branches: [ main ]         # trigger on any push to main
    # (remove paths filter so any commit triggers a deploy)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Build Flutter web
        working-directory: apps/app_flutter
        run: |
          flutter config --enable-web
          flutter pub get
          flutter build web --release

      - name: Deploy to Firebase Hosting (production)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
          entryPoint: "./"
          channelId: live
